### ISSUE TITLE
How do you set up your music library directory?

### ISSUE THREAD

**Issue by BunnyHelp** [ManaZeak/ManaZeak#160] opened 2019-07-13 01:00 UTC
Preface: setting up ManaZeak is pretty much my ever first venture into Linux, so bear with me on some basic questions.
I've (seemingly) mostly setup ManaZeak - I've gotten it to show up in the browser at http://127.0.0.1, and I've logged into an account. But I have a huge question at how the heck to point to a directory that contains my music files. When running `./mzk.sh init` it asked for the path to a music library and music database. Being a noob, I just created two folders in my root directory, named "MusicDatabase" and "MusicLibrary", and typed `~/MusicDatabase` and `~/MusicLibrary` into the terminal. Is that a correct way to type the directory? If not, how do I fix it?
Then, when loading up the webpage and creating an account, the webpage asked for a library name and library path. For the path, I didn't really know what it meant to preface it with /library/, so just typed `/library/`. I've been making folders and copying audio files all over the place, but nothing is showing up in the webpage. 
In the README, you say "/library/ is equal to the path you gave in the `./mzk.sh init` wizard", so if I put audio files into ~/MusicLibrary, to me it sounds like it should show up on the ManaZeak webpage.
Looking through the Wiki, I've seen that you should have 3 main libraries - "ManaZeakArtists, ManaZeakCompilations and ManaZeakMixes" - where are those folders supposed to go? I'm so lost...

![This is what my webpage looks like right now](https://user-images.githubusercontent.com/28743269/61164870-78a52400-a4e7-11e9-9002-59fe367d98ef.png)

![What my docker-compost.yml file looks like](https://user-images.githubusercontent.com/28743269/61164919-fa954d00-a4e7-11e9-85f2-6f4d6f6546d3.png)

**Comment by Squadella** [comment] 2019-07-13 06:05
I think the setup of your application is correct. However the rescan function that exists on the version your using is broken and doesn't work as intended.

The fast and easy way to scan your lib when all the tracks are presents is :
- stop the application `docker-compose stop`
- delete the MusicDatabase folder `sudo rm -r ~/MusicDatabase`
- launch the app again `docker-compose up -d`

We are working on a new update that will come soon and it will ease this process, but it's not ready yet.

Also I realised that we doesn't explained how to configure the passwords of the containers (your database password is 'rootroot').
For changing it : 
- stop the application `docker-compose stop`
- delete the MusicDatabase folder `sudo rm -r ~/MusicDatabase`
- In the docker-compose change the POSTGRES_PASSWORD to the value you want
- In the file located in `ManaZeak/settings.py` go to line 85 and change the value to what you put previously.
- launch the app again `docker-compose up -d`

Hope this fix your problems, if you have other problems feel free to contact us.

**Comment by ArthurBeaulieu** [comment] 2019-11-23 10:09
@BunnyHelp As the docker compose has evovled since your request, I'm closing the issue. If you need further info with the current architecture, DM @Squadella or me, or send a mail to support@manazeak.org

**Closed by ArthurBeaulieu** 2019-11-23 10:09 UTC
Labels: question
